/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IBuyBackInterface extends utils.Interface {
  functions: {
    "dayOfBuyBack()": FunctionFragment;
    "isOpenned()": FunctionFragment;
    "mixTime(string)": FunctionFragment;
    "sellLab(uint256)": FunctionFragment;
    "setStable(address[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "dayOfBuyBack"
      | "isOpenned"
      | "mixTime"
      | "sellLab"
      | "setStable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "dayOfBuyBack",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOpenned", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mixTime",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sellLab",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setStable",
    values: [PromiseOrValue<string>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "dayOfBuyBack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOpenned", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mixTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellLab", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setStable", data: BytesLike): Result;

  events: {};
}

export interface IBuyBack extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBuyBackInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    dayOfBuyBack(overrides?: CallOverrides): Promise<[BigNumber]>;

    isOpenned(overrides?: CallOverrides): Promise<[boolean]>;

    mixTime(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellLab(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStable(
      arg0: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  dayOfBuyBack(overrides?: CallOverrides): Promise<BigNumber>;

  isOpenned(overrides?: CallOverrides): Promise<boolean>;

  mixTime(
    arg0: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellLab(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStable(
    arg0: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    dayOfBuyBack(overrides?: CallOverrides): Promise<BigNumber>;

    isOpenned(overrides?: CallOverrides): Promise<boolean>;

    mixTime(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellLab(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStable(
      arg0: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    dayOfBuyBack(overrides?: CallOverrides): Promise<BigNumber>;

    isOpenned(overrides?: CallOverrides): Promise<BigNumber>;

    mixTime(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellLab(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStable(
      arg0: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    dayOfBuyBack(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOpenned(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mixTime(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellLab(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStable(
      arg0: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
