/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IGLAInterface extends utils.Interface {
  functions: {
    "claim()": FunctionFragment;
    "estimateClaim(address)": FunctionFragment;
    "estimateWithdraw(address)": FunctionFragment;
    "getPhase()": FunctionFragment;
    "getPublicOfferingPrice()": FunctionFragment;
    "getTotalSupply()": FunctionFragment;
    "hardcap()": FunctionFragment;
    "initAt()": FunctionFragment;
    "initialize()": FunctionFragment;
    "initialized()": FunctionFragment;
    "publicOfferingBuy(uint256)": FunctionFragment;
    "publicOfferingEnabledAt()": FunctionFragment;
    "publicOfferingPrice()": FunctionFragment;
    "publicOfferingSharesOf(address)": FunctionFragment;
    "publicOfferingTotalShares()": FunctionFragment;
    "softCap()": FunctionFragment;
    "totalCap()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "unlockAt()": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claim"
      | "estimateClaim"
      | "estimateWithdraw"
      | "getPhase"
      | "getPublicOfferingPrice"
      | "getTotalSupply"
      | "hardcap"
      | "initAt"
      | "initialize"
      | "initialized"
      | "publicOfferingBuy"
      | "publicOfferingEnabledAt"
      | "publicOfferingPrice"
      | "publicOfferingSharesOf"
      | "publicOfferingTotalShares"
      | "softCap"
      | "totalCap"
      | "totalSupply"
      | "unlockAt"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateClaim",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateWithdraw",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getPhase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPublicOfferingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hardcap", values?: undefined): string;
  encodeFunctionData(functionFragment: "initAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicOfferingBuy",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "publicOfferingEnabledAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicOfferingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicOfferingSharesOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "publicOfferingTotalShares",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "softCap", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalCap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unlockAt", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPhase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPublicOfferingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hardcap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicOfferingBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicOfferingEnabledAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicOfferingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicOfferingSharesOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicOfferingTotalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "softCap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlockAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {};
}

export interface IGLA extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGLAInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    estimateClaim(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    estimateWithdraw(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPhase(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPublicOfferingPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTotalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    hardcap(overrides?: CallOverrides): Promise<[BigNumber]>;

    initAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialized(overrides?: CallOverrides): Promise<[boolean]>;

    publicOfferingBuy(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    publicOfferingEnabledAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicOfferingPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    publicOfferingSharesOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    publicOfferingTotalShares(overrides?: CallOverrides): Promise<[BigNumber]>;

    softCap(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalCap(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    unlockAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  claim(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  estimateClaim(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  estimateWithdraw(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPhase(overrides?: CallOverrides): Promise<BigNumber>;

  getPublicOfferingPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  hardcap(overrides?: CallOverrides): Promise<BigNumber>;

  initAt(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialized(overrides?: CallOverrides): Promise<boolean>;

  publicOfferingBuy(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  publicOfferingEnabledAt(overrides?: CallOverrides): Promise<BigNumber>;

  publicOfferingPrice(overrides?: CallOverrides): Promise<BigNumber>;

  publicOfferingSharesOf(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  publicOfferingTotalShares(overrides?: CallOverrides): Promise<BigNumber>;

  softCap(overrides?: CallOverrides): Promise<BigNumber>;

  totalCap(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  unlockAt(overrides?: CallOverrides): Promise<BigNumber>;

  withdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claim(overrides?: CallOverrides): Promise<void>;

    estimateClaim(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateWithdraw(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPhase(overrides?: CallOverrides): Promise<BigNumber>;

    getPublicOfferingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    hardcap(overrides?: CallOverrides): Promise<BigNumber>;

    initAt(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(overrides?: CallOverrides): Promise<void>;

    initialized(overrides?: CallOverrides): Promise<boolean>;

    publicOfferingBuy(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    publicOfferingEnabledAt(overrides?: CallOverrides): Promise<BigNumber>;

    publicOfferingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicOfferingSharesOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publicOfferingTotalShares(overrides?: CallOverrides): Promise<BigNumber>;

    softCap(overrides?: CallOverrides): Promise<BigNumber>;

    totalCap(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    unlockAt(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    estimateClaim(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateWithdraw(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPhase(overrides?: CallOverrides): Promise<BigNumber>;

    getPublicOfferingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    hardcap(overrides?: CallOverrides): Promise<BigNumber>;

    initAt(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialized(overrides?: CallOverrides): Promise<BigNumber>;

    publicOfferingBuy(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    publicOfferingEnabledAt(overrides?: CallOverrides): Promise<BigNumber>;

    publicOfferingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    publicOfferingSharesOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publicOfferingTotalShares(overrides?: CallOverrides): Promise<BigNumber>;

    softCap(overrides?: CallOverrides): Promise<BigNumber>;

    totalCap(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    unlockAt(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    estimateClaim(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimateWithdraw(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPhase(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPublicOfferingPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hardcap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicOfferingBuy(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    publicOfferingEnabledAt(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicOfferingPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicOfferingSharesOf(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicOfferingTotalShares(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    softCap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalCap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unlockAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
