/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBank } from "./IBank";
export type { IBonds } from "./IBonds";
export type { IBuyBack } from "./IBuyBack";
export type { IERC20BurnableMinter } from "./IERC20BurnableMinter";
export type { IGLA } from "./IGLA";
export type { IHelper } from "./IHelper";
export type { ILabs } from "./ILabs";
export type { IMarket } from "./IMarket";
export type { IStakePool } from "./IStakePool";
