/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILabs,
  ILabsInterface,
} from "../../../contracts/interfaces/ILabs";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mintForBuyBack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILabs__factory {
  static readonly abi = _abi;
  static createInterface(): ILabsInterface {
    return new utils.Interface(_abi) as ILabsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILabs {
    return new Contract(address, _abi, signerOrProvider) as ILabs;
  }
}
